# Generated by Django 3.1.7 on 2021-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('h2_tag', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/certificate')),
            ],
        ),
    ]
